package: properties
version: '1.0.0'
author: Andreas Eberhard FriendsOfREDAXO
supportpage: www.redaxo.org/de/forum/

# Durch den Eintrag load: early werden die Properties auch für (fast) alle Addons verfügbar
# load: early

page:
    # title auskommentieren um einen eigenen Haupt-Menüpunkt zu erhalten
    # title: translate:properties
    perm: admin[]
    pjax: true

# pages als Kommentar setzen wenn page: title gesetzt ist für eigenen Haupt-Menüpunkt
pages:
    system/properties: { title: 'translate:properties' }

requires:
    redaxo: '^5.5.0'
